### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by jamesbeedy**
lots of small updates:

* python3 refactor
* requirements.txt
* linting
* README.md updates

### CODE REVIEW

**Comment by jamesbeedy** [comment]
this still needs some work to be fully python3 compat

**Review by rene4jazz — APPROVED** [review]
Nice!

**Comment by jamesbeedy** [comment]
oops, I should have noted its not ready for merge too :) oh well

**Comment by jamesbeedy** [comment]
I think something is up here https://github.com/rene4jazz/visimil/blob/master/server.py#L98 .... it's giving me a 
```
TypeError: 'dict_keys' object does not support indexing
```

**Comment by rene4jazz** [comment]
It might be related to upgrading from Python v2 -> v3.

https://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing

**Pull request merged**
